apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
  labels:
    app: user-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth-service
  template:
    metadata:
      labels:
        app: user-auth-service
    spec:
      containers:
        - name: user-auth-container
          image: user-auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
